[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "4.6.0-rc0"
update_changelog_on_bump = true
version_files = [
    "package.json:version"
]
